[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=-reference-types,-multivalue,-sign-ext,-bulk-memory,-mutable-globals,-nontrapping-fptoint,-tail-call,-extended-const,-relaxed-simd,-threads,-simd128"
]

[build]
target = "wasm32-unknown-unknown"

[profile.release]
opt-level = "z"
lto = true
