[package]
name = "linera-poker-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
linera-sdk.workspace = true
serde.workspace = true
sha2.workspace = true
hex.workspace = true
async-graphql = "7.0"
